/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApplyDocumentsRouteImport } from './routes/apply.documents'
import { Route as ApplyDossierRouteImport } from './routes/apply.dossier'
import { Route as ApplyDprRouteImport } from './routes/apply.dpr'
import { Route as ApplyEligibilityRouteImport } from './routes/apply.eligibility'
import { Route as ApplyLendingPartnerRouteImport } from './routes/apply.lending-partner'
import { Route as ApplyLoanRouteImport } from './routes/apply.loan'
import { Route as ApplySchemesRouteImport } from './routes/apply.schemes'
import { Route as ApplyVoiceRouteImport } from './routes/apply.voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDocumentsRoute = ApplyDocumentsRouteImport.update({
  id: '/apply/documents',
  path: '/apply/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDossierRoute = ApplyDossierRouteImport.update({
  id: '/apply/dossier',
  path: '/apply/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDprRoute = ApplyDprRouteImport.update({
  id: '/apply/dpr',
  path: '/apply/dpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyEligibilityRoute = ApplyEligibilityRouteImport.update({
  id: '/apply/eligibility',
  path: '/apply/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyLendingPartnerRoute = ApplyLendingPartnerRouteImport.update({
  id: '/apply/lending-partner',
  path: '/apply/lending-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyLoanRoute = ApplyLoanRouteImport.update({
  id: '/apply/loan',
  path: '/apply/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySchemesRoute = ApplySchemesRouteImport.update({
  id: '/apply/schemes',
  path: '/apply/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyVoiceRoute = ApplyVoiceRouteImport.update({
  id: '/apply/voice',
  path: '/apply/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/terms': typeof TermsRoute
  '/apply/documents': typeof ApplyDocumentsRoute
  '/apply/dossier': typeof ApplyDossierRoute
  '/apply/dpr': typeof ApplyDprRoute
  '/apply/eligibility': typeof ApplyEligibilityRoute
  '/apply/lending-partner': typeof ApplyLendingPartnerRoute
  '/apply/loan': typeof ApplyLoanRoute
  '/apply/schemes': typeof ApplySchemesRoute
  '/apply/voice': typeof ApplyVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/terms': typeof TermsRoute
  '/apply/documents': typeof ApplyDocumentsRoute
  '/apply/dossier': typeof ApplyDossierRoute
  '/apply/dpr': typeof ApplyDprRoute
  '/apply/eligibility': typeof ApplyEligibilityRoute
  '/apply/lending-partner': typeof ApplyLendingPartnerRoute
  '/apply/loan': typeof ApplyLoanRoute
  '/apply/schemes': typeof ApplySchemesRoute
  '/apply/voice': typeof ApplyVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/consent': typeof ConsentRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/terms': typeof TermsRoute
  '/apply/documents': typeof ApplyDocumentsRoute
  '/apply/dossier': typeof ApplyDossierRoute
  '/apply/dpr': typeof ApplyDprRoute
  '/apply/eligibility': typeof ApplyEligibilityRoute
  '/apply/lending-partner': typeof ApplyLendingPartnerRoute
  '/apply/loan': typeof ApplyLoanRoute
  '/apply/schemes': typeof ApplySchemesRoute
  '/apply/voice': typeof ApplyVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/how-it-works'
    | '/privacy'
    | '/schemes'
    | '/terms'
    | '/apply/documents'
    | '/apply/dossier'
    | '/apply/dpr'
    | '/apply/eligibility'
    | '/apply/lending-partner'
    | '/apply/loan'
    | '/apply/schemes'
    | '/apply/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/how-it-works'
    | '/privacy'
    | '/schemes'
    | '/terms'
    | '/apply/documents'
    | '/apply/dossier'
    | '/apply/dpr'
    | '/apply/eligibility'
    | '/apply/lending-partner'
    | '/apply/loan'
    | '/apply/schemes'
    | '/apply/voice'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/consent'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/how-it-works'
    | '/privacy'
    | '/schemes'
    | '/terms'
    | '/apply/documents'
    | '/apply/dossier'
    | '/apply/dpr'
    | '/apply/eligibility'
    | '/apply/lending-partner'
    | '/apply/loan'
    | '/apply/schemes'
    | '/apply/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ConsentRoute: typeof ConsentRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  SchemesRoute: typeof SchemesRoute
  TermsRoute: typeof TermsRoute
  ApplyDocumentsRoute: typeof ApplyDocumentsRoute
  ApplyDossierRoute: typeof ApplyDossierRoute
  ApplyDprRoute: typeof ApplyDprRoute
  ApplyEligibilityRoute: typeof ApplyEligibilityRoute
  ApplyLendingPartnerRoute: typeof ApplyLendingPartnerRoute
  ApplyLoanRoute: typeof ApplyLoanRoute
  ApplySchemesRoute: typeof ApplySchemesRoute
  ApplyVoiceRoute: typeof ApplyVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/documents': {
      id: '/apply/documents'
      path: '/apply/documents'
      fullPath: '/apply/documents'
      preLoaderRoute: typeof ApplyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/dossier': {
      id: '/apply/dossier'
      path: '/apply/dossier'
      fullPath: '/apply/dossier'
      preLoaderRoute: typeof ApplyDossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/dpr': {
      id: '/apply/dpr'
      path: '/apply/dpr'
      fullPath: '/apply/dpr'
      preLoaderRoute: typeof ApplyDprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/eligibility': {
      id: '/apply/eligibility'
      path: '/apply/eligibility'
      fullPath: '/apply/eligibility'
      preLoaderRoute: typeof ApplyEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/lending-partner': {
      id: '/apply/lending-partner'
      path: '/apply/lending-partner'
      fullPath: '/apply/lending-partner'
      preLoaderRoute: typeof ApplyLendingPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/loan': {
      id: '/apply/loan'
      path: '/apply/loan'
      fullPath: '/apply/loan'
      preLoaderRoute: typeof ApplyLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/schemes': {
      id: '/apply/schemes'
      path: '/apply/schemes'
      fullPath: '/apply/schemes'
      preLoaderRoute: typeof ApplySchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/voice': {
      id: '/apply/voice'
      path: '/apply/voice'
      fullPath: '/apply/voice'
      preLoaderRoute: typeof ApplyVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ConsentRoute: ConsentRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  SchemesRoute: SchemesRoute,
  TermsRoute: TermsRoute,
  ApplyDocumentsRoute: ApplyDocumentsRoute,
  ApplyDossierRoute: ApplyDossierRoute,
  ApplyDprRoute: ApplyDprRoute,
  ApplyEligibilityRoute: ApplyEligibilityRoute,
  ApplyLendingPartnerRoute: ApplyLendingPartnerRoute,
  ApplyLoanRoute: ApplyLoanRoute,
  ApplySchemesRoute: ApplySchemesRoute,
  ApplyVoiceRoute: ApplyVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
